spring:
  datasource:
    url: jdbc:postgresql://3.226.14.5:5432/smartboda2
    username: postgres
    password: igs-dev
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 300000  # 5 minutes
      validation-timeout: 5000
      connection-timeout: 30000
      keepalive-time: 30000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size : 10MB
      max-request-size : 10MB
        
#image:
#  path: "/logo.png"
  
server:
  port: ${PORT:8082}
  ssl:
    key-alias: spring-https
    key-store: classpath:keystore.jks
    key-store-type: JKS
    key-password: intellion
    
cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID:}
      secretKey: ${AWS_SECRET_ACCESS_KEY:}
    region:
      static: us-east-1
    stack:
      auto: false
      
s3:
  bucket:
    name: vugaboda
    
    # Set this to your preferred maximum file size
         # Set this to your preferred maximum request size


        
#logging:
#  level:
#    org:
#      springframework:
#        jdbc:
#          datasource: DEBUG
